services:
  _defaults:
    autowire: true
    autoconfigure: true

  Symfinity\UxBlocksMarketing\:
    resource: '../src/'
    exclude:
      - '../src/SymfinityUxBlocksMarketingBundle.php'
      - '../src/DependencyInjection/'

  Symfinity\UxBlocksMarketing\Twig\UxBlocksMarketingTwigExtension:
    tags: ['twig.extension']

  Symfinity\UxBlocksMarketing\Twig\BlocksMarketingStylesExtension:
    tags: ['twig.extension']

  Symfinity\UxBlocksMarketing\Css\BlocksMarketingCssProvider:
    arguments:
      $packageDir: '%ux_blocks_marketing.package_dir%'
